# frozen_string_literal: true

source "https://rubygems.org"

gem "thin", "~> 1.8"

gem "sorbet", "~> 0.5.6433", group: :development

gem "sorbet-runtime", "~> 0.5.6433"

gem "sqlite3", "~> 1.4"

gem "rubocop", "~> 1.16"

gem "sequel", "~> 5.45"
